<div class="wrap">
<h2>Page Whitelists</h2>
<style>
	.id-column {
		width:2em;
	}
	#wl-lists tfoot tr {
		width:100%;
	}
</style>
<h3><?php _e("General Settings",'page-whitelists'); ?></h3>
<form method="POST" action="">
    <table class="form-table">
    <tbody>
        <tr class="">
        <th scope="row">Default Whitelist Strictness</th>
        <td><fieldset><legend class="screen-reader-text"><span>default whitelist strictness</span></legend>
            <label for="wlist_strict_as_default">
                <input name="wlist_strict_as_default" id="wlist_strict_as_default" value="1"<?php echo $strict_as_default == 1 ? " checked=\"checked\"" : ""; ?> type="checkbox">
                Set new whitelists as 'strict' by default. 
            </label>
            <p class="description">Whitelists will by default not allow assigned users to create new pages.</p>
        </fieldset></td>
        </tr>
        <tr class="">
        <th scope="row">Plugin Compatibility</th>
        <td><fieldset><legend class="screen-reader-text"><span>plugin compatibility</span></legend>
            <label for="wlist_filter_all_listings">
                <input name="wlist_filter_all_listings" id="wlist_filter_all_listings" value="1"<?php echo $filter_all_listings == 1 ? " checked=\"checked\"" : ""; ?> type="checkbox">
                Filter all page listings in Admin area 
            </label>
            <p class="description">Attempts to remove restricted pages from page listings generated by plugins. Doesn't always work correctly (children of restricted pages are not displayed, etc.)</p>
        </fieldset></td>
        </tr>        
    </tbody>
</table>
</form>
<p class="submit"><input name="submit" id="submit" class="button button-primary" value="Save settings" type="submit"></p>
<h3><?php _e("Edit Whitelists",'page-whitelists'); ?></h3>
<table id="wl-lists" class="wp-list-table widefat fixed">
	<thead>
		<tr>
			<th scope="col" class="manage-column id-column">ID</th>
			<th scope="col" class="manage-column"><?php _e("Title",'page-whitelists'); ?></th>
			<th scope="col" class="manage-column"><?php _e("Whitelisted pages",'page-whitelists'); ?></th>
			<th scope="col" class="manage-column"><?php _e("Assigned to roles",'page-whitelists'); ?></th>
			<th scope="col" class="manage-column"><?php _e("Assigned to users",'page-whitelists'); ?></th>
			<th scope="col" class="manage-column"><?php _e("Allow creation of new pages",'page-whitelists'); ?></th>
		</tr>
	</thead>
	<tbody>
		<?php
			
			foreach($lists as $ord=>$list) { ?>
					<tr id="wlist-<?php echo $list->get_id(); ?>" class="whitelist-row <?php echo ($ord%2==0)?'alternate':''; ?>">
			<th scope="row" class="id-column"><?php echo $list->get_id(); ?></th>
			<td><span class="wlist-name"><?php echo $list->get_name(); ?></span>
				<div class="row-actions">
					<span class="edit"><a href="#" id="edit-wlist-<?php echo $list->get_id(); ?>"><?php _e("Edit",'page-whitelists'); ?></a>|</span>
					<span class="trash"><a href="<?php echo wp_create_nonce("delete-wlist-".$list->get_id()); ?>" id="delete-wlist-<?php echo $list->get_id(); ?>"><?php _e("Delete",'page-whitelists'); ?></a></span>
				</div>
			</td>
			<td class="wlist-pages">
			    <?php $pages = $list->get_pages();
                    $page_strings = array();
                    $pagelength = sizeof($pages);
                    for($i = 0; $i < $pagelength; $i++) {
                        if (!is_numeric($pages[$i]->ID)) {
                            continue;
                        }
                        $link = '<a href="'.get_permalink($pages[$i]->ID).'">'.$pages[$i]->post_title.'</a> ('.$pages[$i]->ID.')';
                        if ($i < 5) {
                            $page_strings[] ='<span class="wlist-page">'.$link.', </span>';
                        } elseif ($i == $pagelength - 1) {
                            $page_strings[] ='<span class="wlist-page more"><a href="'.$link.'</span>'; //no comma
                        } else {
                            $page_strings[] ='<span class="wlist-page more"><a href="'.$link.', </span>';
                        }
                    };
                    echo implode("",$page_strings);
                    if (sizeof($pages) > 5) {
                        echo '...<a href="" class="more-link">(more)</a>';
                    }
			    ?>
			</td>
			<td class="wlist-roles"><?php $list->the_roles();	?></td>
			<td class="wlist-users"><?php $list->the_users(); ?></td>
			<td class="wlist-strict"><?php echo ($list->is_strict())?__('no','page-whitelists'):__('yes','page-whitelists');?></td>
		</tr>			
			<?php }; ?>
	</tbody>
</table>
<p><a href="#" id="create-wlist"><?php _e("Create new...",'page-whitelists'); ?></a>
</p>
</div><img id="spinner" src="<?php echo site_url("/wp-admin/images/wpspin_light.gif");?>"/>